version: '3.4'

services:
  creativetim.argon.dotnetcore.free:
    image: ${DOCKER_REGISTRY-}creativetimargondotnetcorefree
    build:
      context: .
      dockerfile: NotificationCenter/Dockerfile
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: 'login'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgresql-data: